name: Rust test on push

on:
  push:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build the ast resources
      run: cargo run -p lox-gen-ast ./lox-rs/src/ --verbose
    - name: Build the interpreter
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
